[features]
seeds = false
skip-lint = false

[programs.localnet]
rwa_tokenization = "FRYwN6vKAVhQNvEcJ8844XxLe3b8zLwivnZk65dnW9HC"

[programs.devnet]
rwa_tokenization = "FRYwN6vKAVhQNvEcJ8844XxLe3b8zLwivnZk65dnW9HC"

[programs.testnet]
rwa_tokenization = "FRYwN6vKAVhQNvEcJ8844XxLe3b8zLwivnZk65dnW9HC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/*"]
